name: Purge jsDelivr cache

on:
  push:
    branches:
      - "main"

jobs:
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@54d0b32057c0d5e7879d37b6cfc0446fbc4aba82